// Bangladesh mock locations (sample). পরে MongoDB থেকে ফেচ করবো।
export const BD_LOCATIONS = [
  "Dhaka",
  "Chittagong",
  "Sylhet",
  "Rajshahi",
  "Khulna",
  "Barishal",
  "Rangpur",
  "Mymensingh",
  "Cox’s Bazar",
  "Comilla",
  "Gazipur",
  "Narayanganj",
  "Tangail",
  "Jessore",
  "Bogra",
  "Dinajpur",
  "Pabna",
  "Feni",
  "Noakhali",
  "Jamalpur",
  "Moulvibazar",
  "Habiganj",
];
